version: '3.9'
services:
  go:
    build:
      context: ./docker/images/go
    container_name: go
    command: 'sleep infinity'
    ports:
      - '8081:8081'
      - '8082:8082'
    volumes:
      - .:/var/server
      - type: volume
        source: /media/sashagvay
        target: /var/server/tmp/usb_mount